#!/bin/bash

set -euo pipefail

BUILD_TYPE="profiler_test"
BUILD_DIR="${BUILD_TYPE}_build"

LIBRARY_INSTANTIATION_LEVEL=0000 #3310 instruction shape [0-3], mma multiplier [0-3,9], cluster shape [0-5], schedule {0,1}; "max" == 9992, see manifest.py init
KERNEL_PATTERN="cutlass3x_sm90_tensorop_gemm_f16_f16_f32_f16_f16*_tn*"
ENABLE_SM90_EXTENDED=ON
CUTLASS_PROFILER_DISABLE_REFERENCE=OFF
CUTLASS_BUILD_FOR_PROFILER_REGRESSIONS=ON

# CMD="cmake -B${BUILD_DIR} -S. \
#   -DCUTLASS_NVCC_ARCHS="90a" \
#   -DCUTLASS_ENABLE_SM90_EXTENDED_MMA_SHAPES=${ENABLE_SM90_EXTENDED}
#   -DCUTLASS_PROFILER_DISABLE_REFERENCE=${CUTLASS_PROFILER_DISABLE_REFERENCE}
#   -DCUTLASS_BUILD_FOR_PROFILER_REGRESSIONS=${CUTLASS_BUILD_FOR_PROFILER_REGRESSIONS}
#   -DCUTLASS_LIBRARY_KERNELS=\"${KERNEL_PATTERN}\" \
#   -DCUTLASS_LIBRARY_INSTANTIATION_LEVEL=${LIBRARY_INSTANTIATION_LEVEL} \
#   -DCUTLASS_UNITY_BUILD_ENABLED=OFF \
#   -DCMAKE_VERBOSE_MAKEFILE=ON \
#   -DCUTLASS_ENABLE_CUBLAS=ON \
#   -DCUTLASS_ENABLE_TESTS=OFF \
#   -DCUTLASS_ENABLE_EXAMPLES=OFF\
#   -GNinja \
#   --debug-output"


# echo $CMD
# # rm -rf ${BUILD_DIR}
# eval $CMD 2>&1 | tee _${BUILD_TYPE}.config.log

BUILD_CMD="cmake --build ${BUILD_DIR} -j4 --target cutlass_profiler --verbose" 
echo $BUILD_CMD

eval $BUILD_CMD 2>&1 | tee _${BUILD_TYPE}.build.log